import { Language } from "../types";

const dictionary = {
  fr: {
    dashboard: "Tableau de Bord",
    orders: "Gestion Commandes",
    stock: "Gestion de Stock",
    logistics: "Logistique",
    finance: "Finance",
    accounting: "Comptabilité",
    marketing: "Marketing (Ads)",
    hr: "Ressources Humaines",
    settings: "Paramètres",
    search: "Rechercher...",
    new_product: "Nouveau Produit",
    new_expense: "Nouvelle Dépense",
    revenue: "Chiffre d'Affaires",
    orders_count: "Total Commandes",
    shipping: "En Livraison",
    returns: "Retours",
    stock_value: "Valeur Stock",
    potential_margin: "Marge Potentielle",
    total_refs: "Total Références",
    actions: "Actions",
    product: "Produit",
    price_buy: "Prix Achat",
    price_sell: "Prix Vente",
    stock_level: "Niveau Stock",
    margin_unit: "Marge / Unité",
    save: "Sauvegarder",
    cancel: "Annuler",
    delete_confirm: "Êtes-vous sûr ?",
    qty: "Quantité",
    welcome: "Bienvenue",
    connect_sheet: "Connecter Google Sheet",
    team_members: "Membres de l'équipe",
    add_member: "Ajouter un membre",
    role: "Rôle",
    salary: "Salaire de base",
    commission: "Comm. par commande",
    net_profit: "Profit Net",
    ads_spend: "Dépenses Pubs",
    roas: "ROI Publicitaire",
    cac: "Coût Acquisition",
    date: "Date",
    description: "Description",
    amount: "Montant"
  },
  en: {
    dashboard: "Dashboard",
    orders: "Orders",
    stock: "Stock",
    logistics: "Logistics",
    finance: "Finance",
    accounting: "Accounting",
    marketing: "Marketing",
    hr: "HR",
    settings: "Settings",
    search: "Search...",
    new_product: "New Product",
    new_expense: "New Expense",
    revenue: "Revenue",
    orders_count: "Orders",
    shipping: "Shipping",
    returns: "Returns",
    stock_value: "Stock Value",
    potential_margin: "Potential Margin",
    total_refs: "Total SKUs",
    actions: "Actions",
    product: "Product",
    price_buy: "Buy Price",
    price_sell: "Sell Price",
    stock_level: "Stock Level",
    margin_unit: "Margin / Unit",
    save: "Save",
    cancel: "Cancel",
    delete_confirm: "Are you sure?",
    qty: "Quantity",
    welcome: "Welcome",
    connect_sheet: "Connect Sheet",
    team_members: "Team",
    add_member: "Add Member",
    role: "Role",
    salary: "Salary",
    commission: "Commission",
    net_profit: "Net Profit",
    ads_spend: "Ads Spend",
    roas: "ROAS",
    cac: "CAC",
    date: "Date",
    description: "Description",
    amount: "Amount"
  },
  ar: {
    dashboard: "لوحة القيادة",
    orders: "الطلبات",
    stock: "المخزون",
    logistics: "اللوجستيات",
    finance: "المالية",
    accounting: "المحاسبة",
    marketing: "التسويق",
    hr: "الموارد البشرية",
    settings: "الإعدادات",
    search: "بحث...",
    new_product: "منتج جديد",
    new_expense: "مصروف جديد",
    revenue: "رقم المعاملات",
    orders_count: "الطلبات",
    shipping: "قيد التوصيل",
    returns: "المرتجعات",
    stock_value: "قيمة المخزون",
    potential_margin: "الهامش المحتمل",
    total_refs: "عدد المراجع",
    actions: "إجراءات",
    product: "المنتج",
    price_buy: "سعر الشراء",
    price_sell: "سعر البايع",
    stock_level: "مستوى المخزون",
    margin_unit: "الهامش",
    save: "حفظ",
    cancel: "إلغاء",
    delete_confirm: "هل أنت متأكد؟",
    qty: "الكمية",
    welcome: "مرحباً",
    connect_sheet: "ربط الشيت",
    team_members: "الفريق",
    add_member: "إضافة عضو",
    role: "الدور",
    salary: "الراتب",
    commission: "العمولة",
    net_profit: "الربح الصافي",
    ads_spend: "مصاريف الإعلانات",
    roas: "عائد الإعلانات",
    cac: "تكلفة الاستحواذ",
    date: "التاريخ",
    description: "الوصف",
    amount: "المبلغ"
  }
};

export const t = (key: keyof typeof dictionary['fr'], lang: Language) => {
  return dictionary[lang][key] || key;
};

export const isRTL = (lang: Language) => lang === 'ar';